[package]
name = "wasm-valgrind-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4.0", features = ["arbitrary-derive"] }
rand="0.3.14"

[dependencies.wasm_valgrind]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "valid_accesses"
path = "fuzz_targets/valid_accesses.rs"
test = false
doc = false

[[bin]]
name = "buggy_accesses"
path = "fuzz_targets/buggy_accesses.rs"
test = false
doc = false